### ISSUE TITLE
akimbo or Akimbo

### ISSUE THREAD

**Issue by SzotsGabor** [jw1912/akimbo#134]
And why?

Just to make sure we use the right name.

Gabor Szots
CCRL

**Comment by jw1912** [comment]
Hi @SzotsGabor,
I prefer lowercase because it matches the repository name, and because in rust you generally define your package name(s) using lowercase in the [Cargo.toml](https://github.com/jw1912/akimbo/blob/main/Cargo.toml), otherwise you get the following warning:
```
warning: crate `Capitalised` should have a snake case name
  |
  = help: convert the identifier to snake case: `capitalised`
  = note: `#[warn(non_snake_case)]` on by default
```

Best wishes,
Jamie
