### ISSUE TITLE
Train own net

### ISSUE THREAD

**Issue by Jochengehtab** [jw1912/akimbo#179]
Hi there, 
i was wondering how i can train a net by myself. I tried to train one and got this done with the bullet trainer. But when i tried to compile the engine with my own net it says the net is too small. It might be helpful if you could show me which parameters you use to train the nets.

Many thanks in advance

**Comment by jw1912** [comment]
@Jochengehtab if you check `common/src/lib.rs` in your local copy of `bullet`, you can see the architecture settings.

If you've left this file unchanged then you can use [this branch](https://github.com/jw1912/akimbo/tree/bullet_default) to load the net.

As for my settings, currently my `common/src/lib.rs` in `bullet` looks as follows:
```rust
/// Input format
///  - Ataxx147
///  - Chess768
///  - ChessBuckets
pub type Input = inputs::Chess768;

/// Size of hidden layer.
pub const HIDDEN: usize = 768;

/// Activation function:
///   - ReLU
///   - CReLU
///   - SCReLU
///   - FastSCReLU
pub type Activation = activation::SCReLU;

/// Output Buckets:
///  - Single
///  - MaterialCount<Buckets>
pub type OutputBucket = outputs::MaterialCount<8>;
```
with the other parts of the file left unchanged.

**Comment by Jochengehtab** [comment]
Hi @jw1912 thanks for your Response. I just realized i messed up the Outputbucket. Thanks for your help.

**Comment by jw1912** [comment]
@Jochengehtab could you give details about how you trained the net? I.e. what command you used to run bullet, and what data you used (how much and source of).

Also if you don't need the `bullet_default` branch I'll delete it later.

**Comment by Jochengehtab** [comment]
> @Jochengehtab could you give details about how you trained the net? I.e. what command you used to run bullet, and what data you used (how much and source of).
> 
> Also if you don't need the `bullet_default` branch I'll delete it later.

I used 50 epochs and a lr-gamma of 0.1 and lr-drop of 12. Also the dataset was very small (26000 Positions i think 7000 winning Positions 15000 Draw Positions and 5000 lossing Positions). I choose such a small dataset because i would make sure that i dont messed anything up. If everything works i will create a larger dataset about 400000 Positions and train it with that.

**Comment by jw1912** [comment]
@Jochengehtab what are you planning on using the net for?

A good heuristic is that for every neuron in the hidden layer, you need *at least* 1 million positions.

So for my current network architecture, I'd need at least 768 million. In actuality, more is generally even better, and at the moment the current net in `main` is trained on 1 billion positions, which I'll hopefully increase to around 1.5 billion in the next few weeks.

**Comment by Jochengehtab** [comment]
> @Jochengehtab what are you planning on using the net for?
> 
> A good heuristic is that for every neuron in the hidden layer, you need *at least* 1 million positions.
> 
> So for my current network architecture, I'd need at least 768 million. In actuality, more is generally even better, and at the moment the current net in `main` is trained on 1 billion positions, which I'll hopefully increase to around 1.5 billion in the next few weeks.

I am making this net for fun because i am interested in nnue chess engines. But thanks for the tip i will increase the Positions to around 400.000.000. And when it is finished and it works quit well i can share it with you.

**Comment by jw1912** [comment]
@Jochengehtab nice, also where are you getting the positions from?

**Comment by Jochengehtab** [comment]
@jw1912 different methods. I generate mostc of the positions with stockfish or Lc0. But around 5 - 8 % are old engine games that where not perfect and games from famous chess personalities Like Petrov, alekhine and so on.

**Comment by jw1912** [comment]
Cool, I'll close this now and delete the branch I made earlier.

**Comment by Jochengehtab** [comment]
@jw1912 OK, where should i contact you when i am finished?

**Comment by jw1912** [comment]
@Jochengehtab apologies, I didn't see this earlier, you can comment on this issue. If you @ me I'll get a notification for it.

**Comment by Jochengehtab** [comment]
> @Jochengehtab apologies, I didn't see this earlier, you can comment on this issue. If you @ me I'll get a notification for it.

@jw1912 but it was my fault because i didn't saw that the issue was closed. But where should i contact you when i have success?

**Comment by jw1912** [comment]
@Jochengehtab you can reply here, I'll get an email notification.
