### ISSUE TITLE
arm64 compilation warning (Win11)

### ISSUE THREAD

**Issue by ArminiusTux** [jw1912/akimbo#211]
Dear @jw1912 ,

just wanted to let you know about the following compilation warning und Windows on ARM64:

<img width="589" alt="akimbo_compilation_warning" src="https://github.com/jw1912/akimbo/assets/44533868/9dbed3b1-59f2-4769-969e-ccbd5323fc8b">

The resulting executable is fine however and working  (although generated in root instead of `target/release`): 😉
![akimbo](https://github.com/jw1912/akimbo/assets/44533868/04515652-f0fd-45a6-969c-3f78fc99a0f8)

**Comment by jw1912** [comment]
@ArminiusTux this is an irrelevant warning.
Additionally the makefile is intended to generate the executable in the root rather than target/release, you will notice the same behaviour from every single engine with an OB-compliant makefile.
